#build
FROM golang:1.19-alpine as build

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

RUN go mod download && go mod verify

COPY . ./

RUN go build -o /golang-rest-api

#deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /golang-rest-api /golang-rest-api

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/golang-rest-api"]
